const SAVE_TRANSACTION = "SAVE_TRANSACTION";
const MODIFY_TRANSACTION_STATE = "MODIFY_TRANSACTION_STATE";
const LOGIN = "LOGIN";
const REGISTER = "REGISTER";
const SAVE_USER = "SAVE_USER";
const SYNC_ACCOUNT = "SYNC_ACCOUNT";
const SAVE_SUPPLY = "SAVE_SUPPLY";
